Page object
vladislav-ruban/java-selenium-testng pull request #2
Opened 2020-09-09 14:07 UTC by vladislav-ruban

Page object implementation

2020-09-14 11:57 UTC, OleksandrMishchenkoGit requested changes

2020-09-14 11:57 UTC, OleksandrMishchenkoGit commented on src/main/java/Pages/CategoryMobilePhonesPage.java
> +        List<Integer> prices = Collectors.collectAndParseToIntResultPrices(searchResultPrices);
Maybe use searchResultPrices.Text?

2020-09-15 09:27 UTC, vladislav-ruban commented on src/main/java/Pages/CategoryMobilePhonesPage.java
> +        List<Integer> prices = Collectors.collectAndParseToIntResultPrices(searchResultPrices);
> Maybe use searchResultPrices.Text?

searchResultPrices contains not only numbers, but also words, so we need to cut everything except numbers out, and parse it to int.

2020-09-15 16:11 UTC, OleksandrMishchenkoGit approved these changes

2020-09-15 16:11 UTC, merged